server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: cloud-provider-payment  # 当前路由的标识, 要求唯一
          uri: http://localhost:8081 #实际路径
          predicates:  # 断言(就是路由转发要满足的条件)
            - Path=/dept/get/** # 当请求路径满足Path指定的规则时,才进行路由转发

eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka/
