server:
  port: 7001

# Eureka配置
eureka:
  instance:
    hostname: eureka1 # Eureka服务端的名字
  client:
    register-with-eureka: false # 表示是否想Eureka中心注册自己
    fetch-registry: false # fetch-registry如果为false，则表示自己为注册中心
    service-url:
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # 关闭自我保护机制