server:
  port: 3344

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ctpower/config.git
          default-label: master
          username: ctpower
          password: ct404404

  rabbitmq:
    host: 192.168.188.50
    port: 5672
    username: admin
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
