server:
  port: 3344

spring:
  application:
    name: cloud-config-center

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ct4433/springcloud-config.git
          default-label: main
          username: ct4433
          password: ct404404


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
