server:
  port: 83

spring:
  application:
    name: nacos-dept-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.50:8848

service-url:
  nacos-user-service: http://nacos-dept-provider