server:
  port: 9002

spring:
  application:
    name: nacos-dept-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.50

management:
  endpoints:
    web:
      exposure:
        include: "*"
