server:
  port: 8082

# mybatis的配置
mybatis:
  type-aliases-package: com.ctpower.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring的配置
spring:
  application:
    name: springcloud-provider-dept

  zipkin:
    base-url: http://192.168.188.50:9411
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


#  #以下为新增
#  druid:
#    # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个，
#    #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
#    test-on-borrow: false
#    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
#    #注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
#    test-while-idle: true
#    # 指明是否在归还到池中前进行检验，注意: 设置为true后如果要生效,
#    #validationQuery参数必须设置为非空字符串
#    test-on-return: false
#    # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.
#    #如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
#    validation-query: select 1



# Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: 8002的eureka描述信息 #修改Eureka上的默认描述信息



#info配置
info:
  app.name: lzh-springcloud #项目的名称
  company.name: com.lzh #公司的名称

